Jungle-CQuiS/frontend

src/modules/room/components/RoomButtons.tsx
src/modules/room/components/RoomTItle.tsx
src/modules/room/components/Team.tsx
src/modules/room/components/TeamUser.tsx
src/pages/multi/room/room.tsx
src/pages/multi/room/styled.ts
src/types/user.ts

- 멀티모드 상세 방
해결한 버그
리팩토링 내역
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
스크린샷은 선택사항입니다!
<br>
사용하지 않은 항목은 모두 지워주세요.

Feat: Multi mode room publishing

---

src/components/modal/room/index.tsx

새로 구현한 기능 및 주요 변경점
방 목록에서 방 만들기 모달 기능을 추가 하였습니다.
비밀번호를 받은 것을 숫자인지 문자인지 4자리 이상인지 확인하는 함수가 길게 나오게 됐는데 혹시 더 좋은 방법이 있나요..?
인생 첫.. 프로젝트 PR입니다...

Feat: Implement Multi mode Create room

---

src/modules/room/components/Team.tsx
src/modules/room/components/TeamUser.tsx
src/pages/multi/room/room.tsx

CSS와 구현 부분에 팀 색깔이 불일치 해서 수정했습니다.
#21 여기서 이상하게 나왔는데, 제가 덜 고쳤었나봐용,,, 
<br>

Fix : Multi Ready Room CSS,HTML sync 수정

---

src/components/modal/room/usercon/index.tsx
src/components/modal/room/usercon/styled.ts
src/modules/room/components/TeamUser.tsx
src/pages/multi/room/room.tsx
src/pages/multi/room/styled.ts

1. css style 코드 수정
```
export const RoomHostIcon = styled.img`
margin : 5px;
`;
export const RoomTeamLeaderIcon = styled.img`
margin : 5px;
`;
```
2. multi : ready room에서  honor, leader, host icon 배치 올바르도록 수정
3. 팀 이름 변경. RED,BLUE -> 1팀, 2팀
빨간팀 명예 박스가 살짝 싱크가 안맞는데, 저 부분은 어떻게 해결해야할지 모르겠어요ㅜㅜ 
```
return isRedTeam ? (
<RoomTeamOneUser onClick={onClick}>
{user ? (
<>
<RoomTeamOneUserName>
{isLeader && <RoomTeamLeaderIcon src="/icons/medal.svg" alt="Badge" />}
{user.name}
{isHost && <RoomHostIcon src="/icons/crown.svg" alt="Badge" />}
</RoomTeamOneUserName>
<RoomTeamOneUserProfile src={user.profileImage} alt={user.name} />
<RoomTeamOneUserHonorWrap>
<RoomTeamOneUserHonor>{user.honor}</RoomTeamOneUserHonor> …
```

Fix : Multi Room CSS 수정

---

src/pages/landing/landing.tsx
src/pages/landing/styled.ts

- 랜딩 페이지 구현
해결한 버그
리팩토링 내역
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
스크린샷은 선택사항입니다!
<br>
사용하지 않은 항목은 모두 지워주세요.

Feat: Landing page publishing

---

src/pages/multi/attack/attack.tsx
src/pages/multi/attack/styled.ts

새로 구현한 기능 및 주요 변경점
멀티모드 공격팀 주제선정하는 페이지 퍼블리싱 해보았습니다..!(팀장 페이지)

Feat: Multi Game Attack Question

---

src/hook/useWebSocket.tsx
src/hook/user.tsx
src/modules/room/components/RoomButtons.tsx
src/modules/room/components/TeamUser.tsx
src/pages/multi/room/room.tsx
src/types/user.ts

localStorage 관리를 위한 UserHook 생성
```
export const useUser = () => {
const [user, setUser] = useState<User | null>(() => {
const saved = localStorage.getItem('user');
return saved ? JSON.parse(saved) : null;
});
//!!!!!!!!!예외 및 보안 처리 필요!!!!!!!!!!!!!!!
const login  = (newUser: User) => {
setUser(newUser);
localStorage.setItem('user', JSON.stringify(newUser));
};
const logout = () => {
setUser(null);
localStorage.removeItem('user');
};
return { user, login , logout };
};
```
사용예시는 아래와 같습니다!
```
// 사용 예시
function Component() {
const { user, login, logout } = useUser();
if (!user) return <div>로그인이 필요합니다 </div>;
return <div>안녕하세요, { user.name }님! </div>;
}
```
보안 관련해서는 추후에 수정 해야 할 것 같아요.
1.   `Room.tsx`에서 통신 부분도 구현되어 …

40 리팩토링 기능 구현 확장성을 위한 커스텀 훅 생성

---

src/components/modal/room/usercontrol/index.tsx

새로 구현한 기능: 유저 클릭시 모달 창에서 볼륨버튼 html 태그만 올렸습니다..!

Feat: Volume button create(HTML)

---

src/components/modal/roomlist/passwordCheck.tsx
src/pages/multi/roomlist/roomlist.tsx

새로 구현한 기능 및 주요 변경점
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다. 최대한 자세히 적어주세요!
해결한 버그
리팩토링 내역
CSS 적용 안해서 몬생김
스크린샷은 선택사항입니다!
<br>
사용하지 않은 항목은 모두 지워주세요.

Feat : Implement Password Check for entering secret room

---

src/modules/room/components/RoomButtons.tsx

멀티모드 대기 방에서 나가기 버튼 구현
이슈 이름 다르게 해서 죄송합니다... 다음에는 꼭 제대로 하겠습니다..

Feat: Implement MultiRoom EXIT button

---

package.json
src/components/modal/room/index.tsx
src/config/api/constants.ts
src/config/api/endpoints/quiz-multi.endpoints.ts
src/config/api/enpoint-creator.ts
src/modules/room/components/RoomButtons.tsx
src/pages/landing/landing.tsx
src/pages/multi/roomlist/roomlist.tsx

- 
API가 변경되었을 경우, 수정하기가 어려워서 위와 같이 리팩토링 하였습니당.
`import { QUIZ_MULTI_ENDPOINTS } from "../../../config/api/endpoints/quiz-multi.endpoints";`
관련 Endpoints를 임포트 한 후
아래의 예시처럼 사용하시면 됩니당.
```
try {
const response = await fetch(QUIZ_MULTI_ENDPOINTS.ROOM.EXIT, {
method: "POST",
headers: {
"Content-Type": "application/json",
},
body: JSON.stringify(requestData),
});
```
<br>

54 리펙토링 api endpont 관리 구조 구축

---

src/App.tsx
src/components/background/styled.ts
src/components/buttons/styled.ts
src/modules/quiz/components/multi/SolvingHeader/SolvingHeader.tsx
src/modules/quiz/components/multi/SolvingHeader/styled.ts
src/modules/quiz/components/multi/UserTags/UserTags.tsx
src/modules/quiz/components/multi/UserTags/styled.ts
src/modules/quiz/components/multi/waiting/WaitingScreen.tsx
src/modules/quiz/components/multi/waiting/styled.ts
src/pages/multi/defend/defend.tsx
src/pages/multi/defend/solving/solving.tsx
src/pages/multi/defend/solving/styled.ts

- [ x] 기능 추가 <br>
- 수비팀 대기 화면 수정
- 문제 풀이 화면 생성

57 퍼블리싱 수비팀 문제 풀이

---

src/App.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/modules/quiz/components/multi/Answer/styled.ts
src/pages/multi/defend/select/select.tsx
src/pages/multi/defend/select/styled.ts

Feat: Publishing answer select page

---

src/components/modal/lookQuestion/index.tsx
src/components/modal/lookQuestion/styled.ts
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx

- 수비팀 정답 선택 화면에서 문제 다시보기 버튼 모달창 생성

Feat: Publishing look question modal

---

src/pages/signup/signup.tsx

회원가입 페이지 구현완료하였습니다.
백엔드와 다시 연결해봐야할 것 같습니다.

Feat: Implement signup page

---

src/pages/loginpage/login.tsx
src/pages/loginpage/protected.tsx
src/pages/signup/signup.tsx

- spring security에 맞는 로그인 로직 수정

Fix: Login page logic

---

src/hook/useRoom.tsx
webpackDevServer.config.js

프로젝트 루트에 webpackDevServer.config.js 파일 생성

Chore : 개발 서버 Websocket 연결시도 방지 코드 작성

---

src/components/modal/room/index.tsx
src/pages/loginpage/login.tsx
src/pages/multi/roomlist/roomlist.tsx

- 로그인 시 uuid 로컬 스토리지 저장
- api 요청 시 header에 accesstoken 보내기

81 로그인 로직 수정

---

src/components/modal/room/countdown/index.tsx
src/components/modal/room/countdown/styled.ts
src/components/modal/room/index.tsx
src/hook/socketEvent.tsx
src/hook/useGameState.tsx
src/hook/useRoom.tsx
src/hook/useRoomUserId.tsx
src/pages/loginpage/login.tsx
src/pages/multi/room/room.tsx
src/pages/multi/roomlist/roomlist.tsx
src/types/game.ts

모두 준비 됨 상태를 서버로부터 받을 경우, time(countdown) 정보를 소켓으로 실시간으로 받아와서, 모달에 매핑하는 것까지
로직 구현. ( 소켓 통신 부분은 아직 작성하지 않음 )

77 멀티 모드 게임 로직 모두 준비 완료 시 게임 시작 카운트 다운 로직 구현

---

src/config/websocket/constants.ts
src/hook/socketEvent.tsx

멀티모드 대기방에서 모든 유저가 준비 상태가 되면 게임 시작하는 로직을 구현하였습니다.

Feat: Implement multi room all-ready

---

package-lock.json
package.json
src/components/modal/room/countdown/index.tsx
src/components/modal/room/usercontrol/index.tsx
src/config/websocket/constants.ts
src/hook/socketEvent.tsx
src/pages/multi/room/room.tsx

모달 창이 띄워졌을때 창 밖을 클릭하거나, ESC등 키보드를 눌렀을 때 나가지지 않게 로직을 추가하였습니다.

87 멀티모드 게임시작 카운트다운 모달 수정

---

src/components/modal/room/usercontrol/index.tsx
src/config/websocket/constants.ts
src/hook/socketEvent.tsx

방장, 팀장 위임하기 및 팀원 강퇴하기 기능 로직 추가하였습니다.(주석으로 처리한 부분은 추가해야할 것 같습니다.)

Feat: Implement Host, Teamleader kick logic

---

src/hook/useOpenVidu.tsx

WebSocket이 마무리가 되면 다시 진행할 수 있도록 하겠습니다..!

Feat: Implement WebRTC session create

---

src/components/modal/room/countdown/index.tsx
src/components/modal/room/countdown/styled.ts
src/config/websocket/constants.ts
src/hook/socketEvent.tsx
src/hook/useRoom.tsx
src/pages/multi/room/room.tsx

멀티모드에서 모든 유저가 준비완료가 되면 모달창이 열리고 
해당 모달창 밖을 클릭하거나 키보드를 입력하더라도 비활성화 상태
기능을 수정하였으며, 
취소하기 버튼 시 대기 방으로 돌아가는 로직을 추가하였습니다.

Feat: Implement Multi game cancel button

---

src/hook/useOpenVidu.tsx

WebSocket 로직과 연결해서 WebRTC 기능 구현(나중에 소켓 열리면 수정 및 추가 필요합니다.)

Feat: WebRTC 와 Websocket 로직 연결 구현

---

src/App.tsx
src/components/modal/room/flipcoin/index.tsx
src/components/modal/room/flipcoin/styled.ts
src/config/api/constants.ts
src/hook/useGameState.tsx
src/hook/useWebSocket.tsx
src/pages/multi/room/room.tsx

97 multireadyroom countdown 종료 후 선공선점 이벤트 logic

---

src/components/modal/room/flipcoin/result/index.tsx
src/pages/multi/room/room.tsx

모든 준비가 완료되면 카운트 다운 모달창 -> 애니메이션 -> 랜덤으로 공격팀이 선정되는 모달창을 구현하였습니다.

105 멀티모드 대기방 선공격팀 모달창 만들기

---

src/hook/socketEvent.tsx
src/hook/useRoom.tsx
src/modules/room/components/Team.tsx

Feat: multi team switch socket seccess

---

src/hook/socketEvent.tsx
src/hook/useGameState.tsx
src/pages/multi/room/room.tsx
src/types/game.ts

모두가 준비 완료 되면, 게임 시작 카운트 다운이 되고,
선공선점 모달이 뜬다.
선공할 팀이 정해지면 게임화면으로 이동한다.
해당 로직을 구현하였습니다.
Game Start Trigger 시 게임 페이지로 이동하는 부분은 하드 코딩 되어있어서, 추후에 서버에서 응답을 받아 진행되는 로직으로 수정해야 합니다.

Feat: game start logic complete

---

src/components/modal/room/countdown/index.tsx
src/hook/useGameState.tsx
src/hook/useRoom.tsx
src/pages/multi/room/room.tsx

필요 없는 import 들 제거했습니다. 
게임 카운트다운 모달 삭제 버튼이 동작이 안되는 이슈가 있었습니다.
원인은 해당 함수는 `roomUserId` 가 필요한데, 인자 전달이 되지 않고 있었습니다.
해당 부분은 수정하였지만, 취소를 누르고 나서 모달이 닫히지 않고 있습니다. @yongsoung 님이 이 부분 구현 추가 부탁드립니당.
자세한 내용은 노션에 적어 놓았습니다.

Refactod: 필요없는 import 제거 및 준비 취소 함수  remapping

---

src/components/modal/room/flipcoin/index.tsx
src/components/modal/room/flipcoin/styled.ts
src/pages/multi/room/room.tsx

게임 시작 시 카운트 모달창이 나오고 그 이후에 코인 애니메이션 기능을 추가하였습니다.
기존에 나왔던 게임시작 전 카운트 모달 창이 다시 나오지 않은 버그 해결하였습니다.
1. flip coin 위치를 계속 태그 안에서 위로 올렸다가 내렸다가 했더니 다른 친구들이 옆으로 밀리는 이상한 상황이 발생해서 어떻게 해야 할지 몰라서 일단 푸시 먼저 했습니다..!
2. 또한, 여기서 코인이 돌아가는 동안 공격팀과 수비팀이 결정이 되는데 임시로 랜덤 함수만 적용해서 추후에 백엔드에서 받아와서 화면에 띄우는 모달창을 구현해야 할 것 같습니다.

116 멀티모드 게임 시작시 lottie 애니메이션 구현

---

src/components/modal/room/flipcoin/result/index.tsx
src/components/modal/room/flipcoin/styled.ts
src/components/modal/roomlist/passwordCheck.tsx
src/pages/multi/room/room.tsx

- []] 기능 삭제 <br>
- 선공 로티 애니메이션 수정
- 선공 표시 모달 수정

122 게임시작 로직 수정

---

src/components/modal/room/countdown/index.tsx
src/pages/multi/room/room.tsx

카운트 다운 모달창이 떴을 때, 취소하기 버튼을 누르면, 모든 유저의 모달창이 꺼지도록 구현하였습니다.
기존에 모든 유저가 준비완료버튼을 누르면 모달창이 뜨지 않는 오류를 해결하였습니다.
외쳐 예람갓..!

Fix: Implement STOP_READY Button

---

src/App.tsx
src/config/websocket/constants.ts
src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/GameStateContext/useGameState.ts
src/contexts/GameUserContext/GameUserContext.tsx
src/contexts/GameUserContext/useGameUser.ts
src/contexts/TeamStateContext/TeamStateContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/hook/readyRoomSocketEvent.tsx
src/hook/useRoom.tsx
src/modules/quiz/components/multi/UserTags/UserTags.tsx
src/modules/room/components/attack/attack.tsx
src/modules/room/components/solving/solving.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/pages/multi/room/room.tsx
src/types/game.ts
src/types/gamedata.ts

1. Provider 위치 변경
```
{/* using web socket */}
<Route element={
<GameStateProvider>
<TeamStateProvider>
<GameUserProvider>
<StompProvider>
<Outlet /> // 하위에 있는 멀티 관련 페이지들을 매핑함.
</StompProvider>
</GameUserProvider>
</TeamStateProvider>
</GameStateProvider>
}
>
//<----생략----> 멀티 관련 페이지 라우트
```
2. Game시작 시 준비방에서 최종 결정된 유저 정보 불러오기( API 테스트 완료 )
3. 유저 정보가 ATTACK 페이지에 렌더링
4. 팀 리더 주제 선택 state 구독 추가.
5. 팀 리더 선택에 따라 같은 팀원에게도 선택 반영되도록 구현 ( 아직 테스트 못함 배포하고 해야함)
1. GamePhase를 전역적으로 관리
```
export default function QuizGamePage() {
const [selectedQuiz, setSelectedQuiz] = useState<Quiz | null>(null);
const { gamePhase , changeGamePhase} = useGameState(); // useState에서 변경함.
const handleCompleteSelection = (quiz: Quiz) => {
setSelectedQuiz(quiz);
changeGamePhase(GamePlayinEvents.SUB_SELECT_END); // 주제 선택 완료 …
```

Multi : 공격, 수비 팀 로직 구현(작업중)

---

src/components/modal/mypage/addQuesttion/index.tsx
src/components/modal/mypage/addQuesttion/styled.ts
src/pages/mypage/addProblem/addProblem.tsx
src/pages/mypage/addProblem/styled.ts
src/types/quiz.ts

마이페이지에서 유저가 직접 문제 생성하고 문제 제출하는 모달 창 구현 및 API 연결
나중에 백엔드와 swagger 양식에 맞게 수정하도록 하겠습니다. (현재 어떻게 들어가있는지 모르겠습니다.)

Feat: Implement Create Problems user

---

src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/GameUserContext/GameUserContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/modules/room/components/attack/attack.tsx

리더가 답을 선택할 떄마다 app 으로 선택한 것을 보냄.
팀원들은 해당 결과를 구독하고 있다.
-> 요청과 구독은 잘되지만, 서버로부터 응답이 안옴. 배포하고 확인할 예정
해결한 버그
leader Select를 GameContext로 관리하도록 변경
서버 테스트는 확인 아직!  요청은 가는것 확인!

141 multi 리더 선택 동기화 

---

src/components/modal/mypage/addQuesttion/index.tsx
src/components/modal/room/countdown/index.tsx
src/hook/pageLeaveHandler.tsx
src/modules/room/components/attack/attack.tsx
src/modules/room/components/solving/solving.tsx
src/pages/multi/defend/defend.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/result/multiResult.tsx
src/pages/multi/room/room.tsx

게임 대기방에서 브라우저 끄거나 새로고침 버튼 누르면 방 나가지는 것을 구현하였습니다.
커스텀 훅을 이용하여 모든 페이지에서 브라우저를 끄거나 새로고침 버튼을 눌렀을 때 방에서 나가지도록 적용 완료 하였습니다.
기존에 게임시작 후 로딩에서 방을 나가지 못하는 것을 해결하였습니다.
뒤로 가기는 추후에 구현 마무리 하도록 하겠습니다.

Feat: 브라우저 창 끄기, 새로고침입력시 컨펌창 생성

---

src/App.tsx
src/config/websocket/constants.ts
src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/GameUserContext/GameUserContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/modules/room/components/attack/attack.tsx
src/modules/room/components/solving/solving.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/types/game.ts
src/types/quiz.ts

1. 공격 팀이 문제 선택 후 수비팀에게 전달 된다.
2. 수비팀은 각각 문제를 풀고 제출한다.
3. 모두 제출이 완료 되면 서버로부터 응답을 받고, 팀원들이 제출한 정답을 Select 페이지에 랜더링한다.
1. 수비팀들이 자신들이 제출한 답을 고르는 페이지에서 문제보기가 있는데, 문제 데이터만 지금 인자로 가져왔고,
모달에 예쁘게???나오게하는건 누그든 부탁드릴게여... @yongsoung  @ll5215 
`selectedQuiz`가 공격이 골라준 문제 데이터에요..! 
```
export default function AnswerSelectComponent( { selectedQuiz ,userAnswers }: SelectAnswerPageProps) {
//<----생략---->
return (
<AnswerSelectContainer>
<BlackButtonSmall onClick={handleOpenModal}>문제보기</BlackButtonSmall>
<AnswerSelectWrap>
{answers.map((answer, index) => (
<AnswerSelectRow key={index} onClick={() => handleSelect(index)}>
<AnswerSelectCheckbox 
src={answer.isSelected ? "/icons/checkbox_filled.svg" : "/icons/checkbox_base.svg"} 
/>
<AnswerSelectText>{answer.value}</AnswerSelectText>
</AnswerSelectRow>
))} …
```

146 multi 수비 화면 context에 의한 동적 랜더링 구현 및 todo 주석 달기( Test 미완료 )

---

src/modules/mypage/components/left/index.tsx
src/modules/mypage/components/left/styled.ts
src/modules/mypage/components/right/index.tsx
src/pages/mypage/styled.ts

현재 마이페이지에서 유저의 정보를 받아오고, 정답률 완성했습니다.
추가로 해야될 작업은 틀렸던 문제 불러오는 것인데 이거는 추후에 백엔드에서 완료가 되면 추가하도록 하겠습니다!

Feat: Implement My page API response

---

src/pages/loginpage/login.tsx

로그인 페이지에서 엔터키를 입력하면 로그인하기 버튼 호출 버튼 실행이 됩니다.

Feat: 로그인 페이지에서 엔터키 입력하면 로그인 버튼 호출

---

src/pages/multi/multi.tsx
src/pages/multi/styled.ts

로그인 이후에 저장되어있던 정보가 검색창에 자동으로 검색이 되는 오류를 수정# PR 타입(하나 이상의 PR 타입을 선택해주세요)
로그인 이후에 저장되어있던 정보가 검색창에 자동으로 검색이 되는 오류를 수정하였습니다.
오류 확인은 제꺼 컴퓨터에서는 확인할 수 없어서 일단 push 먼저 하고 오류 계속 발생할 시에 다시 이슈 생성하도록 하겠습니다.

156 멀티모드 검색창에 자동완성되는 기능 삭제하기

---

src/config/websocket/constants.ts
src/contexts/GameStateContext/GameStateContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/types/game.ts

1. 게임 종료 관련 이벤트 구독 함수에 추가 ( Test X )
2. 권한 관련 조건문 수정

Fix: 수비팀 최종 정답 제출 로직 수정 및 게임 종료 핸들러 함수 설계

---

src/components/modal/mypage/addQuesttion/index.tsx
src/components/modal/room/index.tsx
src/components/modal/roomlist/passwordCheck.tsx
src/components/modal/singleModeSelect/index.tsx
src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/GameUserContext/GameUserContext.tsx
src/contexts/StompContext/StompContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/hook/useRoom.tsx
src/modules/mypage/components/left/index.tsx
src/modules/room/components/attack/attack.tsx
src/modules/single/components/quiz/quizBox/index.tsx
src/pages/multi/room/room.tsx
src/pages/multi/roomlist/roomlist.tsx
src/pages/mypage/addProblem/addProblem.tsx
src/pages/single/quiz/singleQuiz.tsx
src/pages/single/result/singleResult.tsx
src/pages/single/single.tsx

- api 요청 headers에 RefreshToken 추가

Feat: Add refresh token at headers for api request

---

src/components/background/styled.ts
src/modules/mypage/components/left/index.tsx
src/modules/mypage/components/left/styled.ts

- 마이페이지 유저별 카테고리 레벨 표시
- api 요청 주석으로 되어있던 부분은 삭제했습니다.
- 카테고리 레벨에 따라 바 길이 달라지게 식 만들어놨습니다.
```
<MyPagePlayStatisticsBarWrap>
<MyPagePlayStatisticsBarRed  style={{ width: `${(category.level / 3) * 100}%` }} />
</MyPagePlayStatisticsBarWrap>
```

165 퍼블리싱 마이페이지 카테고리별 레벨

---

src/components/modal/index.tsx
src/components/modal/lookQuestion/index.tsx
src/components/modal/lookQuestion/styled.ts
src/components/modal/room/countdown/index.tsx
src/components/quiz/styled.ts
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx

Fix: Fix style for multi game

---

src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/TeamStateContext/TeamStateContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/modules/quiz/components/multi/SolvingHeader/SolvingHeader.tsx
src/modules/room/components/attack/attack.tsx
src/pages/multi/game/quizGame.tsx
src/types/game.ts

169 multi 두 팀간 공수 변경 로직 구현 및 test

---

src/components/modal/index.tsx
src/components/modal/roomlist/passwordCheck.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/defend/select/styled.ts
src/pages/single/result/singleResult.tsx
src/pages/single/single.tsx

Feat: Modal for answer check at multimode

---

src/modules/single/components/quiz/timeAttack/index.tsx

Feat: Single mode time attack

---

src/App.tsx
src/contexts/GameStateContext/GameStateContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/pages/multi/result/multiResult.tsx

1. 라우팅 구조 수정 ( APP.tsx )
2. 게임 종료 후 결과 페이지 이동 구현
3. 라운드 종료 후 퀴즈 결과 모달 카운트 다운 종료 이후 새로운 라운드 시작 로직 구현

176 멀티 모드 게임 종료 로직 구현 ( TEST X )

---

src/components/modal/mypage/addQuesttion/index.tsx
src/modules/mypage/components/left/index.tsx
src/modules/mypage/components/right/index.tsx
src/modules/mypage/components/right/styled.ts
src/pages/mypage/addProblem/addProblem.tsx

- 마이페이지: 틀린 문제 카테고리별로 표시하기 및 정답 표시
- 퀴즈 통계 정답률 % 파싱
- 정답률 바에 데이터를 넣어도 바의 스타일이 변하지 않는 이유는 받는 데이터 자체에 %가 포함되어 있기 때문입니다. ( 예, 0.00%)
이를 식으로 사용하려고 한다면 숫자만 입력해야 하기 때문에 %제거하는 파싱 작업 하였습니다. 
`const numericCorrectRate = parseFloat(userCorrectRate.replace('%', ''));`
` <MyPagePlayStatisticsBarRed style={{ width: `${(category.level / 3) * 100}%` }} />`
- 카테고리 레벨은 디비에 임시 데이터 들어가면 수정하겠습니다.

180 마이페이지 api 연결

---

src/modules/mypage/components/left/styled.ts
src/pages/multi/defend/select/select.tsx
src/pages/multi/result/multiResult.tsx
src/pages/multi/result/styled.ts
src/pages/mypage/styled.ts

183 멀티모드 명예 투표 구현

---

src/modules/mypage/components/left/index.tsx
src/modules/mypage/components/left/styled.ts

- 마이페이지 카테고리별 레벤
- 마이페이지 정답률 없는 유저일떄의 처리

185 마이페이지 카테고리별 레벨 수정

---

src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx

게임 종료 이벤트를 받았을 때 바로 navigate하는 것이 아닌,
결과 모달이 닫히고 나서 이벤트를 검사하도록 변경했습니다.
잘 작동되는지는 배포하고 확인해봐야해서..모름!

Fix: 마지막 라운드 결과 모달 안뜨는 버그 수정( TESTX )

---

src/modules/styled.ts
src/pages/mypage/addProblem/LoadingQuestion.tsx
src/pages/mypage/addProblem/addProblem.tsx
src/pages/mypage/addProblem/styled.ts

마이페이지에서 문제 등록할 때 문제 생성하는 동안 애니메이션 창 띄우기

Feat: Implement Animation before create Question Modal

---

src/components/modal/index.tsx
src/components/modal/mypage/addQuesttion/index.tsx
src/pages/mypage/addProblem/addProblem.tsx

마이페이지에서 문제 생성 시
카테고리에 맞게 문제 생성이 되고, 5가지 주제와 관련 없는 주제의 내용을 입력했을 경우에는 
"주제와 맞지 않은 내용을 입력하셨습니다. 다시 입력해주세요."라는 문구가 생성되며 문제 제출이 되지 않도록 만들었습니다.
문제 생성 개수를 15개로 늘렸습니다.
+ 추가로, 모달 창 밖을 클릭하면 눌리지 않도록 기본설정을 변경하였습니다.

196 마이페이지 문제 생성 화면 수정

---

src/pages/loginpage/login.tsx

Feat: OAuth Google 로그인 버튼 라우트 추가

---

src/contexts/OpenViduContext/OpenViduContext.tsx
src/hook/useRoom.tsx

Connection이 안되는 오류 ->오타 이슈였음! ㅋㅋ

Feat: OpenVidu Session 연결 성공

---

src/pages/multi/roomlist/roomlist.tsx

방이 가득 차있거나 사라진 방을 선택 할 경우
경고창이 뜨도록 구현하였습니다.
추가로 생성된 오류는 issue 생성해서 작업하겠습니다.

Fix: 방이 다 차있거나 방에 인원이 없을 경우 alert창 생성

---

src/App.tsx
src/components/soundEffect/BackgroundMusic.tsx
src/components/soundEffect/VolumeSlider.tsx
src/pages/loginpage/login.tsx
src/pages/loginpage/styled.ts
src/pages/signup/signup.tsx
src/pages/signup/styled.ts

- 구글 로그인 및 회원가입 버튼 삭제
- 배경음악 음량 조절기 추가
*내가 만든 문제 풀기 기능 구현은 추후에 다시 작업 하겠습니다

211 내가 만든 문제 풀기 기능 구현

---

src/hook/gameRoomSocketEvents.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/types/game.ts

Feat: 수비팀 리더 선택 실시간 공유 구현

---

src/hook/useRoom.tsx
src/modules/LoadingScreen.tsx
src/modules/styled.ts
src/pages/multi/room/room.tsx

방 입장할 때 어떤거 떄문에 로딩이 발생하는지 Text로 랜더링 되도록 수정했습니다!

220 멀티 모드 게임 룸 로딩 시 세부 사항 텍스트 넣기

---

src/contexts/GameStateContext/GameStateContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/modules/room/components/solving/solving.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/types/quiz.ts

수비팀 정답 입력 시 다음과 같은 형식으로 전달되고 공유되는 로직으로 변경
```
{
"data": {
quizType: "주관식" (string),
answerList: [
{
"roomUserId": 제출한 roomUser의 id(int),
"answer": 유저가 입력한 정답(string),
"reason": 정답의 이유(string)
},
{
"roomUserId": 제출한 roomUser의 id(int),
"answer": 유저가 입력한 정답(string),
"reason": 정답의 이유(string)
} . . . 
]
},
"message": 성공,
"code": S001
}
또는
{
"data": {
"quizType": "객관식",
"answerList": [
{
"choice": 선택지 번호(int(1~4), 정렬되었으며 요청으로 들어오지 않은 번호는 없음),
"reasonList": ["이유1", "이유2", ...],
"indexList": ["인덱스1", "인덱스2", ...]
},
{
"choice": 선택지 번호(int(1~4), 정렬되었으며 요청으로 들어오지 않은 번호는 없음),
"reasonList": ["이유1", "이유2", ...],
"indexList": ["인덱스1", "인덱스2", ...]
}, ...
]
},
"message": 성공,
"code": S001
}
```

219 멀티 모드 수비팀 정답 입력 로직 및 폼 수정

---

src/pages/loginpage/login.tsx
src/pages/mypage/addProblem/addProblem.tsx
src/pages/mypage/addProblem/styled.ts
src/pages/signup/signup.tsx

로그인, 회원가입 시 이메일 폼 추가 하였습니다.
추가로 기존에 있던 alert을 customAlert으로 변경 완료했습니다.
기존에 로그인 로직이 username과 password로 입력이 되던것을 email로 받아서 수정하였습니다.
기존 Tooltip창 디자인 수정( 줄간격)

226 로그인 회원가입 폼 수정

---

src/components/background/styled.ts
src/pages/landing/styled.ts
src/pages/loginpage/styled.ts
src/pages/mainpage/styled.ts
src/pages/signup/styled.ts
src/pages/single/quiz/singleQuiz.tsx

- 배경제거
- 싱글모드 주관식 답변 undefined 수정

224 싱글모드 수정

---

src/pages/multi/room/room.tsx

Start API 요청 시 오류 나면 재시도 하도록 로직 수정

Bug: Start API 요청 시 오류 나면 재시도 하도록 로직 수정

---

src/pages/multi/roomlist/roomlist.tsx

```
useEffect(() => {
fetchRooms();
}, [fetchRooms]);
useImperativeHandle(ref, () => ({
refreshRooms: fetchRooms
}));
```
컨펌창이 꺼지면 페이지 목록 다시 받아오도록 수정하였습니다.
roomlist 파일 리펙토링

Fix: roomlist.tsx file 리펙토링 및 confirm 창 이후에 목록 창 reload 수정

---

src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/modules/quiz/components/multi/Answer/styled.ts

Feat: 공격팀이 수비팀 화면 공유받을 때 UI 추가

---

src/components/buttons/styled.ts
src/pages/landing/landing.tsx

메인 화면에 Cquis 관련된 information 내용 추가 하였습니다.

Fix: Main page introduction

---

src/components/buttons/emoji/index.tsx
src/components/modal/emogi/animatedEmoji/index.tsx
src/components/modal/emogi/animatedEmoji/styled.ts
src/components/modal/emogi/index.tsx
src/components/modal/lookQuestion/index.tsx
src/components/modal/mypage/addQuesttion/index.tsx
src/contexts/EmojiContext/EmojiContext.tsx
src/contexts/GameStateContext/GameStateContext.tsx
src/contexts/GameUserContext/GameUserContext.tsx
src/contexts/StompContext/StompContext.tsx
src/hook/gameRoomSocketEvents.tsx
src/hook/readyRoomSocketEvent.tsx
src/hook/useEmoji.tsx
src/hook/useRoom.tsx
src/modules/mypage/components/left/index.tsx
src/modules/quiz/components/multi/Answer/AnswerSelect.tsx
src/modules/quiz/components/multi/UserTags/UserTags.tsx
src/modules/quiz/components/multi/UserTags/styled.ts
src/modules/quiz/components/multi/waiting/WaitingScreen.tsx
src/modules/room/components/Team.tsx
src/modules/room/components/attack/attack.tsx
src/modules/room/components/solving/solving.tsx
src/modules/room/components/waitSolving/waitingSolving.tsx
src/pages/multi/defend/select/select.tsx
src/pages/multi/game/quizGame.tsx
src/pages/multi/room/room.tsx
src/pages/mypage/addProblem/addProblem.tsx

이모지 스로틀링 구현
페이지 이동 시 이모지 잔상 남는 버그 수정

253 멀티 모드 이모지 스로틀링 구현

---

src/modules/quiz/components/multi/SolvingHeader/SolvingHeader.tsx
src/modules/room/components/attack/attack.tsx

Fix: Multi Timer 삭제 및 유저 이름 표기( 수비 최종선택에서 )
